### ISSUE TITLE
Change hardcoded library path to relative; add boost library to project, others shouldn't download it themselves

### ISSUE THREAD

**Issue by nikitakunevich** [sashadereh/derekh_chat#10]

**Comment by sashadereh** [comment]
@procion95
What do you mean under "hardcoded library path"? Do you consider that #include <boost/asio.hpp>, for instance, is a hardcoded library path?
I don't quite understand what do you mean under "add boost library to project".

**Comment by nikitakunevich** [comment]
@sashadereh 

> What do you mean under "hardcoded library path"? Do you consider that #include , for instance, is a hardcoded library path?

Yes.

> I don't quite understand what do you mean under "add boost library to project".

I mean that your projects requires some boost libraries, so you should add those to the project, because it is impossible to build project from your repository if you don't already have BOOST, and it is situated somewhere else than e:\Dev\Boost

**Comment by sashadereh** [comment]
In my opinion, pushing compiled Boost libraries here is not a good idea. I tried a good practice when working with Boost - using environment variables.

**Comment by nikitakunevich** [comment]
@sashadereh great, I like this solution :smiley:
